baseURL = "https://350words.com/"
locale = "en-au"
title = "350 Words"
theme = "hugo-simple"
mainSections = ["posts"]

[[menu.main]]
name = "Posts"
pageRef = "/posts"
weight = 10

[params]
description = "Notes, ideas and observations in roughly 350 words."
