baseURL = "https://350words.com/"
locale = "en-au"
title = "350 Words"

[[menu.main]]
name = "Posts"
pageRef = "/posts"
weight = 10

[params]
description = "Strong opinions lightly held."
mainSections = ["posts"]

[params.assets]
  favicon = "book.png"
  svgicon = "book.png"
  apple_touch_icon = "book.png"


[module]
[[module.imports]]
path = "github.com/sergeyklay/gohugo-theme-ed"